INSERT INTO PERSON(PERSON_S.NEXTVAL,'JACK',15,'����');
INSERT INTO PERSON(PERSON_S.NEXTVAL,'MICHAEL',13,'�Ϻ�');
INSERT INTO PERSON(PERSON_S.NEXTVAL,'JIMMY',14,'����');
INSERT INTO PERSON(PERSON_S.NEXTVAL,'TOMMY',12,'����');
INSERT INTO PERSON(PERSON_S.NEXTVAL,'GENIE',19,'����');
INSERT INTO PERSON(PERSON_S.NEXTVAL,'ANDY',42,'�ɶ�');
INSERT INTO PERSON(PERSON_S.NEXTVAL,'LUCY',12,'����');
